### ISSUE TITLE
Heatmap generation is broken

### ISSUE THREAD

**Issue by ben-bougher** [agile-geoscience/pickr#207]
I pulled and redeployed to the dev server and can't generate heatmaps.

'NoneType' object is not iterable
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1536, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1530, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.1/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 310, in post
    self.run_from_request()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 305, in run_from_request
    run(self.request.body)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/deferred/deferred.py", line 147, in run
    return func(*args, **kwds)
  File "/base/data/home/apps/s~pick-this-dev/1.384552306978735921/pickthis.py", line 160, in generate_user_heatmap_layer
    user_layer, cohort = create_user_heatmap_layer(img_obj, user_data)
TypeError: 'NoneType' object is not iterable

**Comment by ben-bougher** [comment]
I won't be able to look into it until tonight ~9 hours from now

**Comment by stevejpurves** [comment]
We have some empty interpretations in the live data whoch we have protected
against elsewhere. Maybe the same thing here, userdata being empty

**Comment by stevejpurves** [comment]
@ben-bougher seen the change, we could use that rescue to delete the offending picks, cleaning up the DB as we go? or maybe that's a bit risky, a future bug could trigger it.

It would be much nicer to just clean up the DB without code changes but we don't have the ability yet, other than maybe stepping through the interpretations on the live DB as admin and deleting ones with no points in the pick.

**Comment by ben-bougher** [comment]
I agree handling datastore deletes inside the heatmap calls is a potential risk.
I made a note in #209 to clean this up if we end up doing datastore cleaning.

@stevejpurves should we close issue and leave the hack for now?

**Comment by stevejpurves** [comment]
go with the hack for now yeah!

On 26 May 2015 at 19:59, ben-bougher <notifications@github.com> wrote:

> I agree handling datastore deletes inside the heatmap calls is a potential
> risk.
> I made a note in #209
> <https://github.com/agile-geoscience/pickr/issues/209> to clean this up
> if we end up doing datastore cleaning.
>
> @stevejpurves <https://github.com/stevejpurves> should we close issue and
> leave the hack for now?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/agile-geoscience/pickr/issues/207#issuecomment-105634956>
> .
>



-- 
españa: 622 195193
uk: 020 32 893 858
@stevejpurves
airpair{}me/stevejpurves
<http://airpair.me/stevejpurves?utm_source=expert&utm_medium=email&utm_content=signature&utm_campaign=airpairme>
skype: steve.purves.home
http://www.linkedin.com/in/stevejpurves
